apiVersion: v1
kind: Service
metadata:
  name: my-udagram-user-api-svc
  labels:
    run: my-udagram-user-api-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-udagram-user-api
